### ISSUE TITLE
Add custom placeholder in the dropzone 

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-file#1]
I would like to add a custom placeholder in the dropzone,

![image](https://cloud.githubusercontent.com/assets/3300779/10456614/82909b5e-71c2-11e5-94a2-87f99c78d768.png)

**Comment by pierbrisson** [comment]
:+1:

**Comment by pierr** [comment]
@JoanaDalmeida As seen with @Bernardstanislas you will improve the component and create a PR cc @pierbrisson
