### ISSUE TITLE
Download file previously uploaded by focus-file

### ISSUE THREAD

**Issue by tadam75** [KleeGroup/focus-file#3]
I have a WebService returning a .Net HttpResponseMessage containing a file (with data, name, mime type) :

![downloadfile](https://cloud.githubusercontent.com/assets/14274196/10510200/d26bd51a-7331-11e5-8404-90a887ac6dc4.PNG)

How can I make this file downloadable ?

Thanks :)

**Comment by pierr** [comment]
@tadamK according to me you file have to be an html link to this file.

**Comment by tadam75** [comment]
Finally we have done it using a MVC Controller :

```
public class MyController : Controller {

    public ActionResult Index(int? id) {

            // Load myFile object using id;
            ContentDisposition content = new ContentDisposition {
            FileName = myFile.Name,
        };
        Response.AppendHeader("Content-Disposition", content.ToString());

        return new FileContentResult(myFile.Data, myFile.ContentType);
    }
}
```

 and a onLineClick event :

```
_onLineClick: function onLineClick(line){
    location.href = './MyController?id=' + line.id;
}
```

**Comment by Bernardstanislas** [comment]
![](http://38.media.tumblr.com/51f524f6fe6b57926999de22ad7dff33/tumblr_npmeujxRBG1t4twpao1_500.gif)
